% Agent-based model of COTS individuals moving across a reef with coral patches
% (c) Karlo Hock, University of Queensland, 2016; updated with descriptions to v2 in 2019

% A model that simulates crown-of-thorns starfish (COTS) individuals performing 
% a random walk across the reef landscape until they reach a coral substrate, when they 
% stop moving and start eating if hungry; the model includes some neat fetures: coral
% substrate is generated by growing colony clusters across a 2-D grid,
% COTS move around more when hungry than when satiated, COTS can sense the proximity of 
% the coral and change their movement behavior, COTS have a reduced appetite in
% winter months due to slower metaoblism, COTS individuals also differ in size (5 categories), class (juvelines, adults), and 
% satiation state - all of which affects their behaviour as well as their movement capabilties; 
% at the end of the simulation the program returns GIF animations of COTS daily movements (number of
% actual cell-to-cell moves within each day will depend on bevhaiour, i.e. satiation etc.) and of coral being gradually eaten; 
% despite the complexity of the implemented behaviours, this is neverthelss just a
% programming/technical demo because many of the relevant parameters of COTS
% movements etc. are unknown/have not been estimated in the field; 
% lack of reliable empirical parameters is also the reason why this 
% model has not been operationalised and/or developed further to include disturbances, COTS control etc. 
% as is, this code/program should not be used to inform management decisions

% Preliminary parameters----------------
% size of the grid
row=50;
col=50;

% target initial coral cover on a grid map
prc_cover=0.2;

% number of initial seeds for coral clusters; clusters can merge if they grow large enough
coral_clusters=5;

% number of COTS individuals/agents to initialise on a map
initial_cotspop=8;

% duration of the simulation; this example simulates 180 days over a single year;
% it is advisable to run very long time series without animations
years=1;
days=180;

% date when the simulation starts; in longer simulations it affects when the seasons will change etc.;
% format is [year, month, day]
start_date=[2010,10,1];

% run the CotsMod agent-based model demo---------
[ cotspop, cotsmap, cotspositions, coralpop, coralmap, coralchange ] = CotsMod( row, col, prc_cover, coral_clusters, initial_cotspop, days, years, start_date  );

% transform the outputs on coral decline into a gif animation with colours showing gradual coral decline due to predation
get_animations(row, col, coralchange, coralpop, cotspositions, cotspop);
